SET SEARCH_PATH TO sae;

DROP TABLE IF EXISTS D_BRAND CASCADE;
DROP TABLE IF EXISTS D_COMPOSITION CASCADE;
DROP TABLE IF EXISTS D_CREATOR CASCADE;
DROP TABLE IF EXISTS D_PRODUCT CASCADE;
DROP TABLE IF EXISTS D_SOLD CASCADE;
DROP TABLE IF EXISTS F_ANALYSE_COMPOSITION CASCADE;
DROP TABLE IF EXISTS F_ANALYSE_SALE CASCADE;

CREATE TABLE D_BRAND (
   ID_D_BRAND           SERIAL               NOT NULL,
   BRAND_NAME           VARCHAR(200)         NOT NULL,
   CONSTRAINT PK_D_BRAND PRIMARY KEY (ID_D_BRAND)
);

CREATE TABLE D_COMPOSITION (
   ID_D_COMPOSITION     	SERIAL               NOT NULL,
   ENERGY_100G          	DECIMAL              NULL,
   ENERGY_KCAL_100G     	DECIMAL              NULL,
   FAT_100G             	DECIMAL              NULL,
   SATURATED_FAT_100G   	DECIMAL              NULL,
   CARBOHYDRATES_100G   	DECIMAL              NULL,
   SUGARS_100G          	DECIMAL              NULL,
   PROTEINS_100G        	DECIMAL              NULL,
   NUTRITION_SCORE_FR_100G  DECIMAL              NULL,
   ECOSCORE_SCORE       	DECIMAL              NULL,
   COMPLETENESS         	DECIMAL              NULL,
   CONSTRAINT PK_D_COMPOSITION PRIMARY KEY (ID_D_COMPOSITION)
);

CREATE TABLE D_CREATOR (
   ID_D_CREATOR         SERIAL               NOT NULL,
   CREATOR_NAME         VARCHAR(300)         NOT NULL,
   CONSTRAINT PK_D_CREATOR PRIMARY KEY (ID_D_CREATOR)
);

CREATE TABLE D_PRODUCT (
   ID_D_PRODUCT         SERIAL               NOT NULL,
   PRODUCT_NAME         VARCHAR(300)         NULL,
   URL_PRODUCT          VARCHAR(700)         NULL,
   IMAGE_URL            VARCHAR(700)         NULL,
   NAME_COUNTRY         VARCHAR(30)          NULL,
   NAME_ECOSCORE_GRADE  VARCHAR(20)          NULL,
   PNNS_NAME            VARCHAR(50)          NULL,
   LETTER_NUTRISCORE    CHAR(1)              NULL,
   NOVA_GROUP           CHAR(1)              NULL,
   CREATED_DATETIME     DATE                 NULL,
   CONSTRAINT PK_D_PRODUCT PRIMARY KEY (ID_D_PRODUCT)
);

CREATE TABLE D_SOLD (
   ID_D_SOLD            SERIAL               NOT NULL,
   SALE_VOLUME          MONEY                NULL,
   SALE_QUANTITY        MONEY                NULL,
   SALE_DATE            DATE                 NULL,
   CONSTRAINT PK_D_SOLD PRIMARY KEY (ID_D_SOLD)
);

CREATE TABLE F_ANALYSE_COMPOSITION (
   ID_F_ANALYSE_COMPOSITION SERIAL           NOT NULL,
   ID_D_PRODUCT         INT4                 NULL,
   ID_D_COMPOSITION     INT4                 NULL,
   ID_D_BRAND           INT4                 NULL,
   ID_D_CREATOR         INT4                 NULL,
   HAVE_ADDITIVE        BOOL                 NULL,
   CONSTRAINT PK_F_ANALYSE_COMPOSITION PRIMARY KEY (ID_F_ANALYSE_COMPOSITION)
);

CREATE TABLE F_ANALYSE_SALE (
   ID_F_ANALYSE_SALE    SERIAL               NOT NULL,
   ID_D_PRODUCT         INT4                 NULL,
   ID_D_SOLD            INT4                 NULL,
   UNIT_PRICE           MONEY                NULL,
   CONSTRAINT PK_F_ANALYSE_SALE PRIMARY KEY (ID_F_ANALYSE_SALE)
);

ALTER TABLE F_ANALYSE_COMPOSITION
   ADD CONSTRAINT FK_F_ANALYS_REFERENCE_D_PRODUC FOREIGN KEY (ID_D_PRODUCT)
      REFERENCES D_PRODUCT (ID_D_PRODUCT)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE F_ANALYSE_COMPOSITION
   ADD CONSTRAINT FK_F_ANALYS_REFERENCE_D_COMPOS FOREIGN KEY (ID_D_COMPOSITION)
      REFERENCES D_COMPOSITION (ID_D_COMPOSITION)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE F_ANALYSE_COMPOSITION
   ADD CONSTRAINT FK_F_ANALYS_REFERENCE_D_BRAND FOREIGN KEY (ID_D_BRAND)
      REFERENCES D_BRAND (ID_D_BRAND)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE F_ANALYSE_COMPOSITION
   ADD CONSTRAINT FK_F_ANALYS_REFERENCE_D_CREATO FOREIGN KEY (ID_D_CREATOR)
      REFERENCES D_CREATOR (ID_D_CREATOR)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE F_ANALYSE_SALE
   ADD CONSTRAINT FK_F_ANALYS_REFERENCE_D_SOLD FOREIGN KEY (ID_D_SOLD)
      REFERENCES D_SOLD (ID_D_SOLD)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE F_ANALYSE_SALE
   ADD CONSTRAINT FK_F_ANALYS_REFERENCE_D_PRODUC FOREIGN KEY (ID_D_PRODUCT)
      REFERENCES D_PRODUCT (ID_D_PRODUCT)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

DROP INDEX IF EXISTS COMPOSITION_PRODUCT_FK;
DROP INDEX IF EXISTS COMPOSITION_COMPOSITION_FK;
DROP INDEX IF EXISTS COMPOSITION_CREATOR_FK;
DROP INDEX IF EXISTS COMPOSITION_BRAND_FK;
DROP INDEX IF EXISTS SALE_SOLD_FK;
DROP INDEX IF EXISTS SALE_PRODUCT_FK;

CREATE INDEX COMPOSITION_PRODUCT_FK ON F_ANALYSE_COMPOSITION (ID_D_PRODUCT);
CREATE INDEX COMPOSITION_COMPOSITION_FK ON F_ANALYSE_COMPOSITION (ID_D_COMPOSITION);
CREATE INDEX COMPOSITION_CREATOR_FK ON F_ANALYSE_COMPOSITION (ID_D_CREATOR);
CREATE INDEX COMPOSITION_BRAND_FK ON F_ANALYSE_COMPOSITION (ID_D_BRAND);
CREATE INDEX SALE_SOLD_FK ON F_ANALYSE_SALE (ID_D_SOLD);
CREATE INDEX SALE_PRODUCT_FK ON F_ANALYSE_SALE (ID_D_PRODUCT);
