SET SEARCH_PATH TO SAE;

CREATE OR REPLACE VIEW V_PRODUCT_DIIM AS
SELECT 
    P.ID_PRODUCT, P.PRODUCT_NAME, P.PRODUCT_BARCODE, 
    P.ENERGY_KCAL_100G, P.FAT_100G, P.SATURATED_FAT_100G, 
    P.CARBOHYDRATES_100G, P.SUGARS_100G, P.PROTEINS_100G, 
    P.NUTRITION_SCORE_FR_100G, P.ECO_SCORE, P.NOVA_GROUP, P.COMPLETENESS, 
    B.BRAND_NAME, C.NAME_COUNTRY, CR.NAME_CREATOR, 
    PG.PNNS_NAME, NG.NUTRISCORE_LETTER, EG.NAME_ECOSCORE_GRADE
FROM PRODUCT P
LEFT JOIN IS_MADE_BY IMB ON P.ID_PRODUCT = IMB.ID_PRODUCT
LEFT JOIN BRAND B ON IMB.ID_BRAND = B.ID_BRAND
LEFT JOIN COUNTRY C ON P.ID_COUNTRY = C.ID_COUNTRY
LEFT JOIN CREATOR CR ON P.ID_CREATOR = CR.ID_CREATOR
LEFT JOIN PNNS_GROUP PG ON P.ID_PNNS = PG.ID_PNNS
LEFT JOIN NUTRISCORE_GRADE NG ON P.ID_NUTRISCORE = NG.ID_NUTRISCORE
LEFT JOIN ECOSCORE_GRADE EG ON P.ID_ECOSCORE_GRADE = EG.ID_ECOSCORE_GRADE;

CREATE OR REPLACE VIEW V_PRODUCT_SALES AS
SELECT P.ID_PRODUCT, P.PRODUCT_NAME, S.ID_SALE, S.SALE_DATE, S.VOLUME_SALES, ISL.QUANTITY
FROM PRODUCT P
JOIN IS_SALE ISL ON P.ID_PRODUCT = ISL.ID_PRODUCT
JOIN SALE S ON ISL.ID_SALE = S.ID_SALE;

CREATE OR REPLACE VIEW V_PRODUCT_BRANDS AS
SELECT P.ID_PRODUCT, B.BRAND_NAME
FROM PRODUCT P
JOIN IS_MADE_BY IMB ON P.ID_PRODUCT = IMB.ID_PRODUCT
JOIN BRAND B ON IMB.ID_BRAND = B.ID_BRAND;

CREATE OR REPLACE VIEW V_PRODUCT_INGREDIENTS AS
SELECT P.ID_PRODUCT, I.INGREDIENT_TAGS
FROM PRODUCT P
JOIN IS_MADE_OF IMO ON P.ID_PRODUCT = IMO.ID_PRODUCT
JOIN INGREDIENT I ON IMO.ID_INGREDIENT = I.ID_INGREDIENT;

CREATE OR REPLACE VIEW V_PRODUCT_ADDITIVES AS
SELECT P.ID_PRODUCT, A.ADDITIVE_TAGS
FROM PRODUCT P
JOIN POSSESES POS ON P.ID_PRODUCT = POS.ID_PRODUCT
JOIN ADDITIVE A ON POS.ID_ADDITIVE = A.ID_ADDITIVE;

CREATE OR REPLACE VIEW V_PRODUCT_PNNS AS
SELECT P.ID_PRODUCT, PG.PNNS_NAME
FROM PRODUCT P
JOIN PNNS_GROUP PG ON P.ID_PNNS = PG.ID_PNNS;

CREATE OR REPLACE VIEW V_PRODUCT_NUTRISCORE AS
SELECT P.ID_PRODUCT, NG.NUTRISCORE_LETTER
FROM PRODUCT P
JOIN NUTRISCORE_GRADE NG ON P.ID_NUTRISCORE = NG.ID_NUTRISCORE;

CREATE OR REPLACE VIEW V_PRODUCT_ECOSCORE AS
SELECT P.ID_PRODUCT, EG.NAME_ECOSCORE_GRADE
FROM PRODUCT P
JOIN ECOSCORE_GRADE EG ON P.ID_ECOSCORE_GRADE = EG.ID_ECOSCORE_GRADE;

CREATE OR REPLACE VIEW V_PRODUCT_COUNTRIES AS
SELECT P.ID_PRODUCT, C.NAME_COUNTRY
FROM PRODUCT P
JOIN COUNTRY C ON P.ID_COUNTRY = C.ID_COUNTRY;

CREATE OR REPLACE VIEW V_PRODUCT_CREATORS AS
SELECT P.ID_PRODUCT, CR.NAME_CREATOR
FROM PRODUCT P
JOIN CREATOR CR ON P.ID_CREATOR = CR.ID_CREATOR;

CREATE OR REPLACE VIEW V_PRODUCT_MAIN AS
SELECT DIIM.*, ING.INGREDIENTS, ADDT.ADDITIVES, SALE.SALE_DATE, SALE.VOLUME_SALES
FROM V_PRODUCT_DIIM DIIM
LEFT JOIN V_PRODUCT_INGREDIENTS ING ON DIIM.ID_PRODUCT = ING.ID_PRODUCT
LEFT JOIN V_PRODUCT_ADDITIVES ADDT ON DIIM.ID_PRODUCT = ADDT.ID_PRODUCT
LEFT JOIN V_PRODUCT_SALES SALE ON DIIM.ID_PRODUCT = SALE.ID_PRODUCT;
